config/routes.rb
FixeddepositApp::Application.routes.draw do

  resources :interestsetups

  resources :interestrates

resources :fixeddeposits do
    resources :interestrates
  end

get "/rateofinterest" => "fixeddeposits#calculate_rateofinterest" , as: "calculate_rateofinterest"

root to: 'fixeddeposits#index'
  
  get "interestrates/new"

  get "interestrates/create"

  get "interestrates/index"

  get "interestrates/show"

  get "interestrates/update"

  get "interestrates/destroy"

  get "interestsetups/new"

  get "interestsetups/create"

  get "interestsetups/index"

  get "interestsetups/show"

  get "interestsetups/update"

  get "interestsetups/destroy"

  get "fixeddeposits/new"

  get "fixeddeposits/create"

  get "fixeddeposits/index"

  get "fixeddeposits/show"

  get "fixeddeposits/update"

  get "fixeddeposits/destroy"

end

app/models/fixeddeposit.rb
class Fixeddeposit < ActiveRecord::Base
  attr_accessible :address, :age, :city, :customername, :dateofbirth, :depositamount, :gender, :interestamount, :maturitydate, :openedon, :periods, :rateofinterest


before_save :set_openedon    
  def set_openedon
    self.openedon = Date.today.strftime("%d/%m/%Y")
  end  

before_save :calculate_age
  def calculate_age
    self.age = ((DateTime.now - self.dateofbirth)/365)
  end

before_save :calculate_maturitydate
  def calculate_maturitydate
    self.openedon = Date.today
     case self.periods
      when 1..365
        self.maturitydate = self.openedon + 1.year
      when 366..730
        self.maturitydate = self.openedon + 2.years
      when 731..1095
        self.maturitydate = self.openedon + 3.years
      when 1096..1460
        self.maturitydate = self.openedon + 4.years
      when 1461..1825
        self.maturitydate = self.openedon + 5.years
      else
        self.maturitydate      
     end
  end

  #before_save :calculate_interestamount
  #def calculate_interestamount
    #self.interestamount = ((self.depositamount.round * self.rateofinterest)/12).round
  #end


  validates :customername, presence: true, format: { with: %r{^[A-Z][a-zA-Z\s]*} }

  validates :periods, presence: true  
  
  validates_inclusion_of :dateofbirth,
      :in => Date.civil(1900, 1, 1)..Date.today,
      :message => "Must be between 1900 and now"   

  validates :address, :city, :gender, :depositamount, presence: true

end

app/models/interestrate.rb
class Interestrate < ActiveRecord::Base

  belongs_to :interestsetup

  attr_accessible :dayfrom, :dayto, :rate, :seniorincrement, :superseniorincrement, :widowincrement, :interestsetup_id

  validates :dayfrom, :dayto, :rate, :seniorincrement, :superseniorincrement, :widowincrement , presence: true
  
end

app/models/interestsetup.rb
class Interestsetup < ActiveRecord::Base
 
  has_many :interestrates

  accepts_nested_attributes_for :interestrates

  attr_accessible :effectivefrom, :effectiveto, :interestrates_attributes

  validates :effectivefrom, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fixeddeposits_controller.rb
class FixeddepositsController < ApplicationController

  def new
    @fixeddeposit =Fixeddeposit.new
  end

  def create
    sleep 2
    @fixeddeposit =Fixeddeposit.new(params[:fixeddeposit])
    if @fixeddeposit.save      
      redirect_to fixeddeposits_path
      flash.now[:success] = "FD Account Opened Successfully!"
    else
      flash[:error] = "Couldn't Open FD"  
      render  'new'
    end
  end

  def index
    @fixeddeposit =Fixeddeposit.order('created_at DESC').paginate(:page => params[:page], :per_page => 8)
  end

  def show
    @fixeddeposit = Fixeddeposit.find(params[:id])
  end

  def edit
    @fixeddeposit = Fixeddeposit.find(params[:id])
  end

  def update
    @fixeddeposit = Fixeddeposit.find(params[:id])

      if @fixeddeposit.update_attributes(params[:fixeddeposit])        
        redirect_to fixeddeposits_path(@fixeddeposit)
        flash.now[:success] = "Updated your FD Account"
      else
        flash[:alert] ="Fill the necessary fields"
        render 'edit'
      end
  end

  def destroy
    @fixeddeposit = Fixeddeposit.find(params[:id])
    @fixeddeposit.destroy    
    redirect_to fixeddeposits_path
    flash.now[:notice] = "Your FD Account Get Deleted"
  end

  def calculate_rateofinterest
    @periods = params[:periods]
    @dateofbirth = params[:dateofbirth]   
    if @age >= 58 && @age < 75
        @rateofinterest = Rateofinterest.select('interestrates.id, interestrates.rate, interestrates.seniorincrement')
      elsif @age >= 75
        @rateofinterest = Rateofinterest.select('interestrates.id, interestrates.rate, interestrates.superseniorincrement') 
      else
        @rateofinterest = Rateofinterest.select('interestrates.id, interestrates.rate')
      end
    respond_to do |format|
      format.html{ redirect_to fixeddeposits_path }    
      format.js
    end
  end

end

app/controllers/interestrates_controller.rb
class InterestratesController < ApplicationController
  def new
    @interestrate = Interestrate.new    
  end

  def create
    @interestrate = Interestrate.find(params[:interestrate])
    @interestrate.save
  end

  def index
    @interestrate = Interestrate.all
  end

  def show
    @interestrate = Interestrate.find(params[:id])
  end

  def edit    
  end

  def update
  end

  def destroy
  end
end

app/controllers/interestsetups_controller.rb
class InterestsetupsController < ApplicationController

  def new
    @interestsetup = Interestsetup.new
    @interestrate = @interestsetup.interestrates.build
  end

  def create
    @interestsetup = Interestsetup.new(params[:interestsetup])
    if @interestsetup.save
      flash[:success] = "New Interest Rate Commenced!"
      redirect_to interestsetup_path(@interestsetup)
    else
      flash[:error] = "Couldn't Setup Interest Rates"  
      render  'new'
    end
  end

  def index
    @interestsetup = Interestsetup.all
  end

  def show
    @interestsetup = Interestsetup.find(params[:id])
  end

  def edit
    @interestsetup = Interestsetup.find(params[:id])
  end

  def update
    @interestsetup = Interestsetup.find(params[:id])
    if @interestsetup.update_attributes(params[:interestsetup])
        flash[:success] = "Updated New Interest Rates"
        redirect_to interestsetups_path(@interestsetup)
      else
        flash[:alert] ="Fill the Necessary Fields"
        render 'edit'
      end
  end

  def destroy
    @interestsetup = Interestsetup.find(params[:id])
    @interestsetup.destroy
    flash[:notice] = "Interest Rate Removed"
    redirect_to interestsetups_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fixeddeposits_helper.rb
module FixeddepositsHelper
end

app/helpers/interestrates_helper.rb
module InterestratesHelper
end

app/helpers/interestsetups_helper.rb
module InterestsetupsHelper
end

app/views/fixeddeposits/_form.html.erb
<style>
body{
padding-top: 60px;
background: url(/assets/inr.png) no-repeat;
background-position: center;
background-size: 100%;
}
</style>



<%= form_for @fixeddeposit do |f| %>  
 
<% if @fixeddeposit.errors.any? %>
<div id="error_explanation">
<h3><%= pluralize(@fixeddeposit.errors.count, "error") %> prohibited this fixeddeposit from being saved:</h3>

<ul>
<% @fixeddeposit.errors.full_messages.each do |error| %>
<li><%= error %></li>
<% end %>
</ul>
</div>
<% end %>
    <%= f.label :customer_name, class:'required' %>
    <%= f.text_field :customername, :placeholder =>'Name' %>

    <%= f.label :date_of_birth, class:'required' %>
    <%= f.date_select :dateofbirth, { :include_blank => true, :start_year => 1900, :end_year => 2014 }, :id => "dateofbirth" %>
   
    <%= f.label :gender, class:'required' %>
    <%= f.select :gender, options_for_select(%w[Male Female]), { :include_blank => true} %>

    <%= f.label :address, class:'required' %>
    <%= f.text_area :address, :id => "address", :cols => 5, :rows => 3 %>

    <%= f.label :city, class:'required' %>
    <%= f.text_field :city, :placeholder =>'City' %>

    <div class="field">
    <%= f.label :Periods, class:'required' %>
    <%= f.number_field :periods, :id => "fixeddeposit_periods", :placeholder => "Days", :class => "input-mini" %>
    <%= button_tag "FD Details", :type => "button", :onclick => "fetchInterest()" %>
    </div>

    <div class="field">
    <%= label_tag 'Rate_Of_Interest' %>
    <%= text_field_tag 'rateofinterest', "", :id => "fixeddeposit_rateofinterest", :disabled => true, :class => "input-medium" %>
    <span class="help-block">auto-generated</span>
    </div>

    <%= f.label :deposit_amount, class:'required' %>
    <%= f.text_field :depositamount, :placeholder =>'0.00' %>
   
    <%= f.label :opened_on %>
    <%= f.text_field :openedon, :disabled => true, :value => Date.today.strftime("%d/%m/%Y"), :class => 'input-medium' %>
<div>      
  </div>
    <%= f.submit "Open FD", class: "btn btn-primary", data: {disable_with: "Opening..."} %>     
    <% end %>
  </div>
</div>

app/views/fixeddeposits/calculate_rateofinterest.js.erb
$("#fixeddeposit_rateofinterest").val(@rate);

app/views/fixeddeposits/create.html.erb
<h1>Fixeddeposits#create</h1>
<p>Find me in app/views/fixeddeposits/create.html.erb</p>

app/views/fixeddeposits/edit.html.erb
<h1>Edit FD Account</h1>
<%= render 'form' %>

app/views/fixeddeposits/index.html.erb
<style>
body{
padding-top: 60px;
background: url(/assets/rupee.jpg) no-repeat;
background-position: center;
background-size: 100%;
}
</style>


<div> 
  <%= link_to "Open FD Account", fixeddeposits_new_path, class: "btn btn-primary" %> 
  <%= link_to "Interest Setup", interestsetups_new_path, class: "btn btn-primary" %> 
</div>

<h6 class= "alert alert-info"><%= page_entries_info @fixeddeposit %></h6>

<table cellpadding = "5" cellspacing ="5" >
  <tr>            
    <th>Opened On</th>
    <th>Customer Name</th>    
    <th>Deposit Amount</th> 
    <th>Customer Age</th>
    <th>Rate Of Interest</th>     
    <th>Periods(In Days)</th>
    <th>Monthly Interest</th>
    <th>Maturity Date</th>       
  </tr>
  <% @fixeddeposit.each do |f| %>
    <tr class="<%= cycle('oddrow', 'evenrow') -%>">                
      <td><%= f.openedon.strftime("%d/%m/%Y") %></td>
      <td><%= link_to f.customername, fixeddeposit_path(f) %></td>  
      <td><%= f.depositamount %></td>
      <td><%= f.age %></td>
      <td><%= f.rateofinterest %>%</td>
      <td><%= f.periods %></td>
      <td><%= f.interestamount %></td>
      <td><%= f.maturitydate.strftime("%d/%m/%Y") %></td>      
      <% end %>       
    </tr>  
</table>
<br/>

<%= will_paginate @fixeddeposit %>

app/views/fixeddeposits/new.html.erb
<h1>New FD Account</h1>
<%= render 'form' %>

app/views/fixeddeposits/show.html.erb
<style>
body{
padding-top: 60px;
background: url(/assets/coins.jpg) no-repeat;
background-position: center;
background-size: 100%;
}
</style>


<div class="hero-unit">
<h5><strong>Customer Name</strong> : <%= @fixeddeposit.customername %></h5>
<h5><strong>Age</strong> : <%= @fixeddeposit.age %></h5>


<hr>
   
<div class="row">
   <div class="span6 customer_left_span_properties">
   <h4><span class="customer">Account details</span></h4>
   <div class="row">
   <div class="span3">
   <strong>Opened On</strong>
   </div>
   <div class="span3"> : <%= @fixeddeposit.openedon.strftime("%d/%m/%Y") %></div>
   </div>
   
   <div class="row">
   <div class="span3">
   <strong>Deposit Amount</strong>
   </div>
   <div class="span3"> : <%= @fixeddeposit.depositamount %></div>
   </div>

   <div class="row">
   <div class="span3">   
   <strong>Periods</strong>
   </div>
   <div class="span3"> : <%= @fixeddeposit.periods %></div>
   </div>

   <div class="row">
   <div class="span3">
   <strong>Rate Of Interest</strong>
   </div>
   <div class="span3"> : <%= @fixeddeposit.rateofinterest %></div>
   </div>

   <div class="row">
   <div class="span3">   
   <strong>Monthly Interest</strong>
   </div>
   <div class="span3"> : <%= @fixeddeposit.interestamount %></div>
   </div>
  
   <div class="row">
   <div class="span3">
   <strong>Maturity Date</strong>
   </div>
   <div class="span3"> : <%= @fixeddeposit.maturitydate.strftime("%d/%m/%Y") %></div>
   </div>
   </div>
   </div>
   </div>
</hr>
</div>
</div>

app/views/fixeddeposits/update.html.erb
<h1>Update FD Account</h1>
<%= render 'form' %>

app/views/interestrates/create.html.erb
<h1>Create</h1>
<p>
  This is the Create page for FD Interest Rates.
</p>

app/views/interestrates/destroy.html.erb
<%= render 'form' %>

app/views/interestrates/edit.html.erb
<h1>Edit Interest Rate</h1>
<%= render 'form' %>

app/views/interestrates/index.html.erb
<h1>Interestrates#index</h1>
<p>Find me in app/views/interestrates/index.html.erb</p>

app/views/interestrates/new.html.erb
<h1>Fixed Deposit Interest Rates</h1>
<%= render 'form' %>

app/views/interestrates/show.html.erb
<h1>Interestrates#show</h1>
<p>Find me in app/views/interestrates/show.html.erb</p>

app/views/interestrates/update.html.erb
<h1>Update Fixed Deposit Interest Rates</h1>
<%= render 'form' %>

app/views/interestsetups/_form.html.erb
<%= form_for @interestsetup do |f| %>  
 
<% if @interestsetup.errors.any? %>
<h4>Couldn't create Interest Rates</h4>
<ul>
<% @interestsetup.errors.full_messages.each do |error| %>
<li><%= error %></li>
<% end %>
</ul>
<% end %>

    <%= f.label :effectivefrom, class:'required' %>
    <%= f.date_select :effectivefrom, { :include_blank => true, :start_year => 1993, :end_year => 2014 } %>

    <%= f.label :effectiveto %>
    <%= f.date_select :effectiveto, { :include_blank => true, :start_year => 1993, :end_year => 2014 } %>

    
<h3>Interest Rates</h3>
<% (1..5).each do |num| %>
    <%= f.fields_for "interestrates_attributes[#{num}]" do |ir| %>
<table class='table condensed-table'>
<tr>
<td>Days From</td>
<td>Days To</td>
<td>Rate</td>
<td>Senior Increment</td>
<td>Super Senior Increment</td>
<td>Widow Increment</td>
</tr>
<tr>
<td><%= ir.number_field :dayfrom, :class => 'input-mini' %></td>
<td><%= ir.number_field :dayto, :class => 'input-mini' %></td>
<td><%= ir.text_field :rate, :class => 'input-mini', :id => "interestrates_rate" %></td>
<td><%= ir.text_field :seniorincrement, :class => 'input-mini', :id => "interestrates_seniorincrement" %></td>
<td><%= ir.text_field :superseniorincrement, :class => 'input-mini', :id => "interestrates_superseniorincrement" %></td>
<td><%= ir.text_field :widowincrement, :class => 'input-mini', :id => "interestrates_widowincrement" %></td>
</tr>
</table>
<%end%>
<% end %>
  <div>    
  </div>
    <%= f.submit "Create Setup", class: "btn btn-primary" %>     
    <% end %>
  </div>
</div>

app/views/interestsetups/create.html.erb
<h1>Create</h1>
<p>
  This is the Create page for FD Interest setup.
</p>

app/views/interestsetups/edit.html.erb
<h1>Edit Interest Setup</h1>
<%= render 'form' %>

app/views/interestsetups/index.html.erb
<h1>Fixed Deposit Setup </h1>

<table cellpadding = "5" cellspacing ="5" >
  <h3>Today's Interest Rate</h3>
  <tr>            
    <th>Days From</th>
    <th>Days To</th>    
    <th>Rate</th> 
    <th>Senior Increment</th>
    <th>Super Senior Increment  </th>     
    <th>Widow Increment</th>
  </tr>
<% @interestsetup.each do |is| %>
    <tr>                
      <td><%=  %></td>
      <td><%=  %></td>  
      <td><%=  %></td>
      <td><%=  %></td>
      <td><%=  %></td>
      <td><%=  %></td>
      <% end %></td>         
    </tr>  
</table>
<br/>

app/views/interestsetups/new.html.erb
<h1>Fixed Deposit Interest Setup</h1>
<%= render 'form' %>

app/views/interestsetups/show.html.erb
<h1><%= link_to "Interest Setup", interestsetups_new_path, class: "btn btn-primary" %></h1>


<h5><strong>Effective From</strong> : <%= @interestsetup.effectivefrom.strftime("%d/%m/%Y") %></h5>
<h5><strong>Effective To</strong> : <%= @interestsetup.effectiveto %></h5>




<table cellpadding = "5" cellspacing ="5" >
  <tr>            
    <th>Days From</th>
    <th>Days To</th>    
    <th>Rate</th> 
    <th>Senior Increment</th>
    <th>Super Senior Increment</th>     
    <th>Widow Increment</th>     
  </tr>
  <% @interestsetup.interestrates.each do |irs| %>
    <tr>                
      <td><%= irs.dayfrom %></td>
      <td><%= irs.dayto %></td>  
      <td><%= irs.rate %>%</td>
      <td><%= irs.seniorincrement %>%</td>
      <td><%= irs.superseniorincrement %>%</td>
      <td><%= irs.widowincrement %>%</td>      
      </td>  
      <% end %>       
    </tr>  
</table>
<br/>

app/views/interestsetups/update.html.erb
<h1>Update Fixed Deposit Interest Setup</h1>
<%= render 'form' %>

app/views/layouts/_footer.html.erb
<footer class="footer">  
  <small>

  </small>  
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "FIXED DEPOSIT",fixeddeposits_path, id: "logo" %>
    </div>
  </div>
   
       
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fixed Deposit</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div id="header">
    <%= render 'layouts/header' %>
    </div>
      <div class="container">
      <% flash.each do |key, value| %>
        <br /><br />
      <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
          <div id="footer">

      </div></div>
</body>
</html>